### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by c0decat** [c0decat/mpris-remote#1]
- [x] Add web ui
- [x] Add album art
- [ ] Code cleanups in js code
- [ ] Make pebble client
